"""
KG validation script for the Fashion domain.

Runs after build_kg_fashion.py to verify the semantic correctness of the generated
knowledge graph against the original preprocessed data.

Two layers of validation:

  1. Sampled spot checks: pick random triples from the KG and verify they
     correspond to actual rows in the source data.

  2. Global invariants: properties that must hold across the whole graph,
     such as "no leakage" or "no duplicates".
"""

import os
import logging
import random
import pandas as pd
import json

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# ---- Paths ---------------------------------------------------------------- #
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
FASHION_ROOT = os.path.abspath(os.path.join(THIS_DIR, ".."))

# Outputs generated by build_kg_fashion.py
BASE_DIR = os.path.join(FASHION_ROOT, "data")
PROCESSED_DIR = os.path.join(BASE_DIR, "processed")

# Source files for validation
FILTERED_INTERACTIONS = os.path.join(BASE_DIR, "interactions_5_core_filtered.csv")
VALID_ITEMS_METADATA = os.path.join(BASE_DIR, "metadata_valid_items.json")
ALSO_BUY_PAIRS = os.path.join(BASE_DIR, "also_buy_pairs.json")

# KG files to validate
KG_PATH = os.path.join(PROCESSED_DIR, "kg_train.tsv")
TASKA_VALID = os.path.join(PROCESSED_DIR, "taskA_valid.tsv")
TASKA_TEST = os.path.join(PROCESSED_DIR, "taskA_test.tsv")

# ---- Config --------------------------------------------------------------- #
COL_USER = 'reviewerID'
COL_ITEM = 'asin'

N_SAMPLES_PER_RELATION = 20  # number of triples to spot-check per relation

random.seed(42)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def strip_prefix(node, prefix):
    """Remove the type prefix from a node ID (e.g. 'item_1234' -> '1234')."""
    expected = prefix + '_'
    if not node.startswith(expected):
        raise ValueError(f"Node {node} does not start with expected prefix {expected}")
    return node[len(expected):]


def load_data():
    """Load all necessary data files for validation."""
    logger.info("Loading source data for validation...")

    if not os.path.exists(FILTERED_INTERACTIONS):
        logger.error(f"Source file not found: {FILTERED_INTERACTIONS}")
        logger.error("Please run build_kg_fashion.py first.")
        return None, None, None

    df_interactions = pd.read_csv(FILTERED_INTERACTIONS)

    with open(VALID_ITEMS_METADATA, 'r') as f:
        metadata = json.load(f)

    with open(ALSO_BUY_PAIRS, 'r') as f:
        also_buy = json.load(f)

    logger.info(f"Loaded {len(df_interactions):,} filtered interactions.")
    logger.info(f"Loaded metadata for {len(metadata):,} items.")
    logger.info(f"Loaded {len(also_buy):,} also_buy pairs.")

    return df_interactions, metadata, also_buy


# --------------------------------------------------------------------------- #
# Spot checks per relation
# --------------------------------------------------------------------------- #

def check_belongs_to(metadata, kg_df, n_samples):
    """Verify that (item, belongs_to, category) triples are correct."""
    logger.info("\n--- Spot check: belongs_to ---")
    sub = kg_df[kg_df['relation'] == 'belongs_to'].sample(n=n_samples, random_state=1)

    failures = 0
    for _, row in sub.iterrows():
        item_id = strip_prefix(row['head'], 'item')
        category_id = strip_prefix(row['tail'], 'category')

        if item_id not in metadata:
            logger.error(f"  FAIL: Item {item_id} from KG not found in metadata.")
            failures += 1
            continue

        # Category is the last element of the list
        expected_category = metadata[item_id]['categories']

        if expected_category != category_id:
            logger.error(
                f"  FAIL: For item {item_id}, expected category "
                f"'{expected_category}' but got '{category_id}'"
            )
            failures += 1

    if failures == 0:
        logger.info(f"  PASS: all {n_samples} 'belongs_to' triples are correct.")
    return failures


def check_belongs_to_brand(metadata, kg_df, n_samples):
    """Verify that (item, belongs_to_brand, brand) triples are correct."""
    logger.info("\n--- Spot check: belongs_to_brand ---")
    sub = kg_df[kg_df['relation'] == 'belongs_to_brand'].sample(n=n_samples, random_state=2)

    failures = 0
    for _, row in sub.iterrows():
        item_id = strip_prefix(row['head'], 'item')
        brand_id = strip_prefix(row['tail'], 'brand')

        if item_id not in metadata:
            logger.error(f"  FAIL: Item {item_id} from KG not found in metadata.")
            failures += 1
            continue

        expected_brand = metadata[item_id].get('brand', 'N/A')

        if expected_brand != brand_id:
            logger.error(
                f"  FAIL: For item {item_id}, expected brand "
                f"'{expected_brand}' but got '{brand_id}'"
            )
            failures += 1

    if failures == 0:
        logger.info(f"  PASS: all {n_samples} 'belongs_to_brand' triples are correct.")
    return failures


def check_compatible_with(also_buy_pairs, kg_df, n_samples):
    """Verify that (item, compatible_with, item) triples come from also_buy data."""
    logger.info("\n--- Spot check: compatible_with ---")
    sub = kg_df[kg_df['relation'] == 'compatible_with'].sample(n=n_samples, random_state=3)

    # Create a lookup set for faster checking
    also_buy_set = set()
    for item1, related_items in also_buy_pairs.items():
        for item2 in related_items:
            # Store both directions for symmetric check
            also_buy_set.add(tuple(sorted((item1, item2))))

    failures = 0
    for _, row in sub.iterrows():
        item1_id = strip_prefix(row['head'], 'item')
        item2_id = strip_prefix(row['tail'], 'item')

        pair = tuple(sorted((item1_id, item2_id)))
        if pair not in also_buy_set:
            logger.error(
                f"  FAIL: Pair ({item1_id}, {item2_id}) "
                f"not found in source also_buy data."
            )
            failures += 1

    if failures == 0:
        logger.info(f"  PASS: all {n_samples} 'compatible_with' triples found in source data.")
    return failures


# --------------------------------------------------------------------------- #
# Global invariants
# --------------------------------------------------------------------------- #

def check_no_duplicates(kg_df):
    """The KG must have no duplicate triples."""
    logger.info("\n--- Invariant: no duplicates ---")
    n_dup = kg_df.duplicated().sum()
    if n_dup > 0:
        logger.error(f"  FAIL: {n_dup:,} duplicate triples found")
        return 1
    logger.info("  PASS: no duplicates")
    return 0


def check_node_prefix_consistency(kg_df):
    """For each relation, the head and tail prefixes must be consistent."""
    logger.info("\n--- Invariant: head/tail prefix consistency per relation ---")

    expected = {
        'compatible_with': ('item', 'item'),
        'belongs_to': ('item', 'category'),
        'belongs_to_brand': ('item', 'brand'),
    }

    failures = 0
    for rel, (h_pref, t_pref) in expected.items():
        sub = kg_df[kg_df['relation'] == rel]

        if not len(sub):
            logger.warning(f"  SKIP: No triples found for relation '{rel}'")
            continue

        bad_h = (~sub['head'].str.startswith(h_pref + '_')).sum()
        bad_t = (~sub['tail'].str.startswith(t_pref + '_')).sum()

        if bad_h > 0 or bad_t > 0:
            logger.error(
                f"  FAIL: relation '{rel}' has {bad_h} bad heads, {bad_t} bad tails"
            )
            failures += 1
        else:
            logger.info(f"  PASS: '{rel}' uses ({h_pref}_*, {t_pref}_*)")

    return failures


def check_no_taska_leakage(kg_df, valid_df, test_df):
    """Task A holdout triples must NOT appear in the KG."""
    logger.info("\n--- Invariant: no Task A leakage ---")
    kg_set = set(map(tuple, kg_df.values))

    leaks_v = sum(1 for r in valid_df.values if tuple(r) in kg_set)
    leaks_t = sum(1 for r in test_df.values if tuple(r) in kg_set)

    if leaks_v > 0 or leaks_t > 0:
        logger.error(
            f"  FAIL: {leaks_v} valid + {leaks_t} test triples leaked into KG"
        )
        return 1

    logger.info("  PASS: no Task A leakage detected")
    return 0


def check_compatible_with_completeness(also_buy_pairs, metadata, kg_df, valid_df, test_df):
    logger.info("\n--- Invariant: compatible_with split is complete ---")

    # Valid items are those that appear in the KG
    cw_kg   = kg_df[kg_df['relation'] == 'compatible_with']
    val_cw  = valid_df  # already contains only compatible_with
    test_cw = test_df

    kg_items = set(cw_kg['head'].str.replace('item_', '')) | \
           set(cw_kg['tail'].str.replace('item_', ''))
    val_items = set(val_cw['head'].str.replace('item_', '')) | \
                set(val_cw['tail'].str.replace('item_', ''))
    test_items = set(test_cw['head'].str.replace('item_', '')) | \
                set(test_cw['tail'].str.replace('item_', ''))
    valid_items = kg_items | val_items | test_items

    # Source pairs filtered to valid items and cross-category pairs only
    source_pairs = set()
    for item1, related_items in also_buy_pairs.items():
        if item1 not in valid_items:
            continue

        cat1 = metadata.get(item1, {}).get('categories')

        for item2 in related_items:
            if item2 not in valid_items:
                continue

            cat2 = metadata.get(item2, {}).get('categories')

            # Discard same-category pairs, exactly as done in build_kg
            if cat1 is None or cat2 is None or cat1 == cat2:
                continue

            source_pairs.add(
                tuple(sorted((f"item_{item1}", f"item_{item2}")))
            )

    # Pairs in KG + validation + test
    union = set()
    for h, t in list(zip(cw_kg['head'], cw_kg['tail'])) + \
                list(zip(val_cw['head'], val_cw['tail'])) + \
                list(zip(test_cw['head'], test_cw['tail'])):
        union.add(tuple(sorted((h, t))))

    missing = source_pairs - union
    extra   = union - source_pairs

    if len(missing) == 0 and len(extra) == 0:
        logger.info(
            f"  PASS: split covers all {len(source_pairs):,} valid pairs"
        )
        return 0

    logger.error(f"  FAIL: missing {len(missing):,}, extra {len(extra):,}")

    if missing:
        logger.error(f"    sample missing: {list(missing)[:3]}")

    if extra:
        logger.error(f"    sample extra: {list(extra)[:3]}")

    return 1


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    logger.info("=" * 70)
    logger.info("FASHION KG VALIDATION")
    logger.info("=" * 70)

    # Load source data
    df_interactions, metadata, also_buy = load_data()
    if df_interactions is None:
        return

    # Load generated KG files
    try:
        kg_df = pd.read_csv(KG_PATH, sep='\t')
        valid_df = pd.read_csv(TASKA_VALID, sep='\t')
        test_df = pd.read_csv(TASKA_TEST, sep='\t')

    except FileNotFoundError as e:
        logger.error(f"File not found: {e.filename}")
        logger.error(
            "Make sure you have run build_kg_fashion.py and the output files exist."
        )
        return

    logger.info(f"Loaded KG   : {len(kg_df):,} triples")
    logger.info(f"Loaded valid: {len(valid_df):,} triples")
    logger.info(f"Loaded test : {len(test_df):,} triples")

    total_failures = 0

    # ---- Layer 1: spot checks ----
    logger.info("\n" + "=" * 70)
    logger.info("LAYER 1: SAMPLED SPOT CHECKS")
    logger.info("=" * 70)

    total_failures += check_belongs_to(
        metadata,
        kg_df,
        N_SAMPLES_PER_RELATION
    )
    total_failures += check_belongs_to_brand(
        metadata,
        kg_df,
        N_SAMPLES_PER_RELATION
    )
    total_failures += check_compatible_with(
        also_buy,
        kg_df,
        N_SAMPLES_PER_RELATION
    )

    # ---- Layer 2: global invariants ----
    logger.info("\n" + "=" * 70)
    logger.info("LAYER 2: GLOBAL INVARIANTS")
    logger.info("=" * 70)

    total_failures += check_no_duplicates(kg_df)
    total_failures += check_node_prefix_consistency(kg_df)
    total_failures += check_no_taska_leakage(
        kg_df,
        valid_df,
        test_df
    )
    total_failures += check_compatible_with_completeness(
        also_buy,
        metadata,
        kg_df,
        valid_df,
        test_df
    )

    # ---- Verdict ----
    logger.info("\n" + "=" * 70)

    if total_failures == 0:
        logger.info("ALL CHECKS PASSED")
    else:
        logger.error(
            f"{total_failures} CHECKS FAILED -- review the log above"
        )

    logger.info("=" * 70)


if __name__ == "__main__":
    main()